// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyVocaList.Infra;

#nullable disable

namespace MyVocaList.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515132000_RefactorCatalogAndAddLyrics")]
    partial class RefactorCatalogAndAddLyrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("MyVocaList.Domain.Entity.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<string>("ExternalProvider")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<bool>("HasManualEdits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<string>("NameNormalized")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_Artists_ExternalId");

                    b.HasIndex("NameNormalized")
                        .IsUnique()
                        .HasDatabaseName("IX_Artists_NameNormalized");

                    b.ToTable("Artists", (string)null);
                });

            modelBuilder.Entity("MyVocaList.Domain.Entity.Catalog", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArtistId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("Catalog", (string)null);
                });

            modelBuilder.Entity("MyVocaList.Domain.Entity.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<bool>("QueueActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("MyVocaList.Domain.Entity.EventParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PersonId");

                    b.ToTable("EventParticipations");
                });

            modelBuilder.Entity("MyVocaList.Domain.Entity.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Absences")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("BirthdayDayMonth")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<Guid?>("ExternalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<string>("FullNameNormalized")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<int>("Participations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Persons_Email");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("IX_Persons_ExternalId");

                    b.HasIndex("FullNameNormalized")
                        .HasDatabaseName("IX_Persons_FullNameNormalized");

                    b.HasIndex("FullNameNormalized", "BirthdayDayMonth")
                        .IsUnique()
                        .HasDatabaseName("IX_Persons_Name_Birthday")
                        .HasFilter("[BirthdayDayMonth] IS NOT NULL");

                    b.ToTable("People");
                });

            modelBuilder.Entity("MyVocaList.Domain.Entity.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtistId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<string>("ExternalProvider")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<string>("FeaturedArtists")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<bool>("HasManualEdits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lyrics")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<string>("TitleNormalized")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("IX_Songs_ExternalId");

                    b.HasIndex("ArtistId", "TitleNormalized")
                        .IsUnique()
                        .HasDatabaseName("IX_Songs_ArtistId_TitleNormalized");

                    b.ToTable("Songs", (string)null);
                });

            modelBuilder.Entity("MyVocaList.Domain.Entity.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .UseCollation("NOCASE_NOACCENT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .UseCollation("NOCASE_NOACCENT");

                    b.HasKey("Id");

                    b.ToTable("SystemConfigurations");
                });

            modelBuilder.Entity("MyVocaList.Domain.Entity.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE_NOACCENT");

                    b.HasKey("Id");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("MyVocaList.Domain.Entity.Catalog", b =>
                {
                    b.HasOne("MyVocaList.Domain.Entity.Artist", "Artist")
                        .WithMany("CatalogEntries")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyVocaList.Domain.Entity.Song", "Song")
                        .WithMany("CatalogEntries")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MyVocaList.Domain.Entity.Event", b =>
                {
                    b.HasOne("MyVocaList.Domain.Entity.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("MyVocaList.Domain.Entity.EventParticipation", b =>
                {
                    b.HasOne("MyVocaList.Domain.Entity.Event", "Event")
                        .WithMany("Participations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyVocaList.Domain.Entity.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MyVocaList.Domain.Entity.Song", b =>
                {
                    b.HasOne("MyVocaList.Domain.Entity.Artist", "OriginalArtist")
                        .WithMany("OriginalSongs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalArtist");
                });

            modelBuilder.Entity("MyVocaList.Domain.Entity.Artist", b =>
                {
                    b.Navigation("CatalogEntries");

                    b.Navigation("OriginalSongs");
                });

            modelBuilder.Entity("MyVocaList.Domain.Entity.Event", b =>
                {
                    b.Navigation("Participations");
                });

            modelBuilder.Entity("MyVocaList.Domain.Entity.Song", b =>
                {
                    b.Navigation("CatalogEntries");
                });

            modelBuilder.Entity("MyVocaList.Domain.Entity.Venue", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
